# Setup
version_name: mtpl_pascal_vitLp16
out_dir: "./logs/"

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 1
valBatch: 4
nworkers: 0
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 1000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 1.e-5
   weight_decay: 1.e-6
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}

# Model
model: TaskPrompter
backbone: TaskPrompter_vitL
head:  conv
embed_dim: 768
final_embed_dim: 768
prompt_len: 1
chan_nheads: 16
use_ctr: False

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Task Loss
loss_kwargs:
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0

# Prompt Loss
lambda_spe: 5.
lambda_spe_norm: 0.1
lambda_sha: 5.
lambda_sha_norm: 0.1